In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
df=pd.read_csv("C:\\Users\\gopus\\Downloads\\output.csv")
df.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0    Review  1000 non-null   object
 1   Liked    1000 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 15.8+ KB


In [14]:
df.isnull().sum()

 Review    0
Liked      0
dtype: int64

In [15]:
df.duplicated().sum()

4

In [16]:
df=df.drop_duplicates()

In [17]:
df.duplicated().sum()

0

In [19]:
from collections import Counter
import re
def get_words(text):
    text=text.lower()
    text=re.sub(r"[^a-zA-Z\s]","",text)
    words=text.split()
    return words
all_words=df[" Review"].apply(get_words).sum()
word_counts=Counter(all_words)
print(word_counts.most_common(10))

[('the', 583), ('and', 389), ('i', 301), ('was', 294), ('a', 237), ('to', 219), ('is', 171), ('this', 141), ('it', 132), ('of', 127)]


In [20]:
all_words

['wow',
 'loved',
 'this',
 'place',
 'crust',
 'is',
 'not',
 'good',
 'not',
 'tasty',
 'and',
 'the',
 'texture',
 'was',
 'just',
 'nasty',
 'stopped',
 'by',
 'during',
 'the',
 'late',
 'may',
 'bank',
 'holiday',
 'off',
 'rick',
 'steve',
 'recommendation',
 'and',
 'loved',
 'it',
 'the',
 'selection',
 'on',
 'the',
 'menu',
 'was',
 'great',
 'and',
 'so',
 'were',
 'the',
 'prices',
 'now',
 'i',
 'am',
 'getting',
 'angry',
 'and',
 'i',
 'want',
 'my',
 'damn',
 'pho',
 'honeslty',
 'it',
 'didnt',
 'taste',
 'that',
 'fresh',
 'the',
 'potatoes',
 'were',
 'like',
 'rubber',
 'and',
 'you',
 'could',
 'tell',
 'they',
 'had',
 'been',
 'made',
 'up',
 'ahead',
 'of',
 'time',
 'being',
 'kept',
 'under',
 'a',
 'warmer',
 'the',
 'fries',
 'were',
 'great',
 'too',
 'a',
 'great',
 'touch',
 'service',
 'was',
 'very',
 'prompt',
 'would',
 'not',
 'go',
 'back',
 'the',
 'cashier',
 'had',
 'no',
 'care',
 'what',
 'so',
 'ever',
 'on',
 'what',
 'i',
 'had',
 'to',
 's

In [22]:
df["tokens"]=df[" Review"].str.split()

In [23]:
df["token_len"]=df["tokens"].apply(len)

In [24]:
df.head()

Review  Liked  \
0                           Wow... Loved this place.      1   
1                                 Crust is not good.      0   
2          Not tasty and the texture was just nasty.      0   
3  Stopped by during the late May bank holiday of...      1   
4  The selection on the menu was great and so wer...      1   

                                              tokens  token_len  
0                      [Wow..., Loved, this, place.]          4  
1                            [Crust, is, not, good.]          4  
2  [Not, tasty, and, the, texture, was, just, nas...          8  
3  [Stopped, by, during, the, late, May, bank, ho...         15  
4  [The, selection, on, the, menu, was, great, an...         12

In [25]:
from nltk.corpus import stopwords

In [26]:
stop_words=set(stopwords.words("english"))

In [27]:
df['tokens_no_stopwords']=df['tokens'].apply(lambda tokens:[word for word in tokens if word not in stop_words])

In [28]:
from nltk.stem import PorterStemmer
stemmer=PorterStemmer()
df['tokens_stemmed']=df['tokens_no_stopwords'].apply(lambda tokens:[stemmer.stem(word) for word in tokens])

In [29]:
df.head()

Review  Liked  \
0                           Wow... Loved this place.      1   
1                                 Crust is not good.      0   
2          Not tasty and the texture was just nasty.      0   
3  Stopped by during the late May bank holiday of...      1   
4  The selection on the menu was great and so wer...      1   

                                              tokens  token_len  \
0                      [Wow..., Loved, this, place.]          4   
1                            [Crust, is, not, good.]          4   
2  [Not, tasty, and, the, texture, was, just, nas...          8   
3  [Stopped, by, during, the, late, May, bank, ho...         15   
4  [The, selection, on, the, menu, was, great, an...         12   

                                 tokens_no_stopwords  \
0                            [Wow..., Loved, place.]   
1                                     [Crust, good.]   
2                      [Not, tasty, texture, nasty.]   
3  [Stopped, late, May, bank, holiday, Rick, Stev...   
4             [The, selection, menu, great, prices.]   

                                      tokens_stemmed  
0                             [wow..., love, place.]  
1                                     [crust, good.]  
2                       [not, tasti, textur, nasty.]  
3  [stop, late, may, bank, holiday, rick, steve, ...  
4                [the, select, menu, great, prices.]

In [33]:
df["cleaned"]=df["tokens_stemmed"].apply(lambda x:" ".join(x))

In [34]:
df["cleaned"].head()

0                                   wow... love place.
1                                          crust good.
2                              not tasti textur nasty.
3    stop late may bank holiday rick steve recommen...
4                        the select menu great prices.
Name: cleaned, dtype: object

In [35]:
from sklearn.feature_extraction.text import CountVectorizer

In [36]:
vects=CountVectorizer(binary=True)

In [37]:
bags=vects.fit_transform(df["cleaned"])
print("vocabulary:", vects.get_feature_names_out())
print("bow matrix:\n", bags.toarray())

vocabulary: ['00' '10' '100' ... 'yummi' 'yummy' 'zero']
bow matrix:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [41]:
y=df["Liked"]
x=bags

In [49]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(796, 1887)
(796,)
(200, 1887)
(200,)


In [50]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix,classification_report


nb=BernoulliNB()
nb.fit(x_train,y_train)
y_pred=nb.predict(x_test)

In [51]:
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print(f"Precision:{precision_score(y_test, y_pred):.4f}")
print(f"Recall:   {recall_score(y_test, y_pred):.4f}")
print(f"F1 Score: {f1_score(y_test, y_pred):.4f}")
print('confusion matrix:',confusion_matrix(y_test, y_pred))
print('Classification Report:',classification_report(y_test, y_pred))

Accuracy: 0.7250
Precision:0.6545
Recall:   0.8090
F1 Score: 0.7236
confusion matrix: [[73 38]
 [17 72]]
Classification Report:               precision    recall  f1-score   support

           0       0.81      0.66      0.73       111
           1       0.65      0.81      0.72        89

    accuracy                           0.72       200
   macro avg       0.73      0.73      0.72       200
weighted avg       0.74      0.72      0.73       200



In [52]:
import pickle
with open("review.pkl", "wb") as file:
    pickle.dump(nb, file)

In [53]:
with open("review.pkl", "rb") as file:
    loaded_model = pickle.load(file)

In [54]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pickle

# Fit the vectorizer to your training data
vect = TfidfVectorizer()
vect.fit(df['cleaned']) 

# Save the FITTED vectorizer
pickle.dump(vect, open('vectorize.pkl', 'wb'))

In [55]:
# Define the filename
pkl_filename = "vectorizer.pkl"

# Open the file in write-binary mode ('wb') and dump the vectorizer
with open(pkl_filename, 'wb') as file:
    pickle.dump(vect, file)

print(f"Vectorizer successfully saved to {pkl_filename}")

Vectorizer successfully saved to vectorizer.pkl


In [56]:
sample_vectorized = vect.transform(['its a good and helpful product'])

# 2. Predict using the vectorized data
prediction = loaded_model.predict(sample_vectorized)

print(prediction)

[1]


In [57]:
sample_vectorized = vect.transform(['its a bad and helpful product'])

# 2. Predict using the vectorized data
prediction = loaded_model.predict(sample_vectorized)

print(prediction)

[0]
